# ===========================================
# RGProtect - Конфигурация плагина
# Версия: 1.0
# ===========================================

# Настройки блока привата
protect-block:
  # Материал блока привата
  material: "DIAMOND_BLOCK"
  # Название в инвентаре
  display-name: "&aБлок привата для &e{player}"
  # Описание (лор)
  lore:
    - "&7Поставьте этот блок чтобы"
    - "&7защитить территорию"
    - ""
    - "&eВладелец: &f{player}"
    - "&7Размер: &f3x3x3"

# Настройки создания регионов
region-creation:
  # Включать ли подсветку границ по умолчанию для новых регионов
  borders-enabled-by-default: true

# Настройки таймера регионов
region-timer:
  # Включена ли система таймеров
  enabled: true
  # Начальное время жизни региона (в минутах)
  initial-lifetime-minutes: 5
  # Максимальное время жизни региона (в часах)
  max-lifetime-hours: 168  # 7 дней

# Настройки временного расширения по высоте
height-expansion:
  # Включена ли система временного расширения по высоте
  enabled: true
  # Максимальное время расширения (в часах)
  max-expansion-hours: 72  # 3 дня

# Настройки региона
region:
  # Базовый размер региона
  size:
    x: 3
    y: 3
    z: 3

# Лимиты
limits:
  # Максимальное количество регионов на игрока
  max-regions-per-player: 5

# Настройки голограмм
hologram:
  # Включены ли голограммы
  enabled: true
  # Высота голограммы над блоком
  height-offset: 1.5
  # Интервал обновления (в тиках, 20 = 1 секунда)
  update-interval: 20
  # Текст голограммы
  lines:
    - "&6Регион игрока: &e{player}"
    - "&7Создан: &f{date}"
    - "&7Время жизни: &f{timer}"
    - "&dРасширение ↕: &f{height_expansion}"

# Настройки визуализации
visualization:
  # Включена ли визуализация
  enabled: true
  # Физические границы из блоков
  physical-borders:
    # Включены ли физические границы
    enabled: true
    # Материал для границ
    material: "RED_WOOL"
    # Предотвращать ломание границ
    prevent-breaking: true
    # Настройки размещения границ
    placement:
      # Стратегия размещения:
      # - surface_contact: всегда на земле
      # - below_center: на 1 блок ниже центра
      # - visibility_based: с приоритетом видимости, но на земле
      strategy: "visibility_based"
      # Максимальная глубина поиска земли
      max_depth_search: 20
      # Максимальная высота поиска
      max_height_search: 10
      # Заменять ли растительность
      replace_vegetation: true

# Настройки расширения регионов
region-expansion:
  # Включено ли расширение регионов
  enabled: true
  # Максимальный уровень расширения
  max-level: 10
  # Базовый размер для расчета уровней
  base-size:
    x: 3
    y: 3
    z: 3
  # Цены за каждый уровень расширения
  prices:
    1: 1000.0    # 3x3x3 -> 5x5x5
    2: 2500.0    # 5x5x5 -> 7x7x7
    3: 5000.0    # 7x7x7 -> 9x9x9
    4: 10000.0   # 9x9x9 -> 11x11x11
    5: 20000.0   # 11x11x11 -> 13x13x13
    6: 35000.0   # 13x13x13 -> 15x15x15
    7: 50000.0   # 15x15x15 -> 17x17x17
    8: 75000.0   # 17x17x17 -> 19x19x19
    9: 100000.0  # 19x19x19 -> 21x21x21
    10: 150000.0 # 21x21x21 -> 23x23x23

  # Настройки проверки коллизий
  collision-check:
    # Проверять коллизии перед расширением
    enabled: true
    # Проверять пересечения с собственными регионами
    check-own-regions: false
    # Показывать детальную информацию о конфликтах
    detailed-conflict-info: true
    # Предлагать альтернативные решения
    suggest-alternatives: true

# Настройки защиты от коллизий
collision-protection:
  # Включена ли защита
  enabled: true
  # Строгий режим (запрещает даже пересечения своих регионов)
  strict-mode: false
  # Минимальное расстояние между регионами разных игроков
  min-distance-between-regions: 0
  # Детальные сообщения об ошибках
  detailed-error-messages: true
  # Показывать координаты в сообщениях об ошибках
  show-coordinates-in-errors: true
  # Показывать размеры регионов в сообщениях
  show-sizes-in-errors: true
  # Анализировать все типы пересечений
  analyze-all-intersections: true

# Система защитных флагов
flag-protection:
  # Включить систему защитных флагов
  enabled: true

  # Доступные флаги для активации
  flags:
    # Защита от взрывов
    explosion-immunity:
      name: "&c&lЗащита от взрывов"
      description: "Полная защита от всех взрывов"
      material: "TNT"
      duration: 3600  # в секундах (1 час)
      price: 5000.0
      worldguard-flags:
        - "tnt:deny"
        - "other-explosion:deny"
        - "creeper-explosion:deny"

    # Защита от мобов
    mob-immunity:
      name: "&6&lЗащита от мобов"
      description: "Мобы не могут войти в регион"
      material: "ZOMBIE_HEAD"
      duration: 7200  # 2 часа
      price: 3000.0
      worldguard-flags:
        - "mob-spawning:deny"
        - "entity-spawn:deny"

# Настройки меню
menu:
  # Название меню
  title: "&6&lМеню региона"
  # Размер меню (9, 18, 27, 36, 45, 54)
  size: 27
  # Элементы меню
  items:
    # Кнопка информации
    info:
      slot: 11
      material: "BOOK"
      name: "&b&lИнформация о регионе"
      lore:
        - ""
        - "&7Владелец: &e{owner}"
        - "&7Размер: &e{size}"
        - "&7Создан: &e{date}"
        - ""
        - "&8ID: {region_id}"

    # Кнопка расширения
    expand:
      slot: 13
      material: "EMERALD"
      name: "&a&lРасширить регион"
      lore:
        - ""
        - "&7Текущий размер: &e{current_size}"
        - "&7Новый размер: &a{next_size}"
        - ""
        - "&7Уровень: &f{level}/{max_level}"
        - "&7Цена: &6{price} монет"
        - ""
        - "&eНажмите для расширения!"

    # Кнопка закрытия
    close:
      slot: 15
      material: "BARRIER"
      name: "&c&lЗакрыть меню"
      lore:
        - ""
        - "&7Нажмите чтобы закрыть"

    # Кнопка временного расширения по высоте
    height-expansion:
      slot: 16
      material-active: "ELYTRA"
      material-inactive: "FEATHER"
      name-active: "&d&lВременное расширение ↕"
      name-inactive: "&7&lРасширение по высоте"
      lore-active:
        - ""
        - "&7Регион временно расширен"
        - "&7до максимальной высоты мира."
        - ""
        - "&7Оставшееся время:"
        - "&f{time}"
        - ""
        - "&eНажмите для управления"
      lore-inactive:
        - ""
        - "&7Временно расширить регион"
        - "&7до максимальной высоты мира."
        - ""
        - "&7Это позволит строить"
        - "&7на любой высоте в регионе."
        - ""
        - "&eНажмите для активации"

    # Кнопка переключения подсветки границ
    borders-toggle:
      slot: 20
      material-enabled: "GLOWSTONE"
      material-disabled: "REDSTONE_LAMP"
      name-enabled: "&e&lПодсветка границ: &a&lВКЛ"
      name-disabled: "&e&lПодсветка границ: &c&lВЫКЛ"
      lore-enabled:
        - ""
        - "&7Границы региона подсвечены"
        - "&7красной шерстью для удобства."
        - ""
        - "&eНажмите, чтобы выключить"
        - "&7подсветку границ региона."
        - ""
        - "&8Границы можно включить обратно"
        - "&8в любой момент через это меню."
      lore-disabled:
        - ""
        - "&7Границы региона сейчас скрыты."
        - "&7Регион всё ещё защищён!"
        - ""
        - "&aНажмите, чтобы включить"
        - "&7подсветку границ региона."
        - ""
        - "&8Это полезно для визуализации"
        - "&8размеров вашего региона."

    # Кнопка защитных флагов
    flag-protection:
      slot: 12
      material: "SHIELD"
      name: "&e&lЗащита региона"
      lore:
        - "&7Управление защитными флагами"
        - "&7и временными усилениями"
        - ""
        - "&e⚡ Нажмите для настройки!"

    # Кнопка времени жизни
    lifetime:
      slot: 24
      material-active: "CLOCK"
      material-inactive: "BARRIER"
      name-active: "&5&lВремя жизни региона"
      name-inactive: "&7&lТаймер отключен"
      lore-active:
        - ""
        - "&7Оставшееся время:"
        - "&f{time}"
        - ""
        - "&eНажмите, чтобы продлить"
        - "&7время жизни региона."
        - ""
        - "&8Регион будет удален после"
        - "&8истечения времени жизни!"
      lore-inactive:
        - ""
        - "&7Этот регион был создан"
        - "&7до включения системы таймеров."
        - ""
        - "&8Таймеры применяются только"
        - "&8к новым регионам."

    # Кнопка удаления
    delete:
      slot: 22
      material: "TNT"
      name: "&c&lУдалить регион"
      lore:
        - ""
        - "&cВНИМАНИЕ!"
        - "&7Это действие удалит регион"
        - "&7и вернет блок привата."
        - ""
        - "&cРегион будет удален навсегда!"
        - ""
        - "&eНажмите для удаления"

    # Декоративные элементы
    filler:
      enabled: true
      material: "GRAY_STAINED_GLASS_PANE"
      name: "&r"
      slots: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 17, 18, 19, 21, 23, 25, 26]

# Меню времени жизни
lifetime-menu:
  # Название меню
  title: "&5&lПродление времени жизни"
  # Размер меню
  size: 27
  # Элементы меню
  items:
    # Информация о времени
    info:
      slot: 4
      material: "CLOCK"
      name: "&b&lВремя жизни региона"
      lore:
        - ""
        - "&7Регион: &e{region}"
        - "&7Осталось времени:"
        - "&f{time}"
        - ""
        - "&8Выберите опцию продления"
        - "&8времени жизни ниже."

    # Кнопка возврата
    back:
      slot: 22
      material: "ARROW"
      name: "&c&lНазад"
      lore:
        - ""
        - "&7Вернуться в меню региона"

    # Декоративные элементы
    filler:
      enabled: true
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&r"
      slots: [0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 19, 20, 21, 23, 24, 25, 26]

  # Опции продления времени
  time-options:
    # Опция 1 час
    hour1:
      slot: 11
      minutes: 60
      price: 1000.0
      material: "IRON_INGOT"
      name: "&a+1 час"
      lore:
        - ""
        - "&7Продлить время жизни"
        - "&7региона на &e1 час"
        - ""
        - "&7Цена: &6{price} монет"
        - ""
        - "&eНажмите для покупки!"

    # Опция 3 часа
    hours3:
      slot: 13
      minutes: 180
      price: 2500.0
      material: "GOLD_INGOT"
      name: "&a+3 часа"
      lore:
        - ""
        - "&7Продлить время жизни"
        - "&7региона на &e3 часа"
        - ""
        - "&7Цена: &6{price} монет"
        - ""
        - "&eНажмите для покупки!"

    # Опция 6 часов
    hours6:
      slot: 15
      minutes: 360
      price: 5000.0
      material: "DIAMOND"
      name: "&a+6 часов"
      lore:
        - ""
        - "&7Продлить время жизни"
        - "&7региона на &e6 часов"
        - ""
        - "&7Цена: &6{price} монет"
        - ""
        - "&eНажмите для покупки!"

# Меню временного расширения по высоте
height-expansion-menu:
  # Название меню
  title: "&d&lВременное расширение ↕"
  # Размер меню
  size: 27
  # Элементы меню
  items:
    # Информация о расширении
    info:
      slot: 4
      material: "ELYTRA"
      name: "&b&lВременное расширение"
      lore:
        - ""
        - "&7Регион: &e{region}"
        - "&7Текущая высота: &f{current_height}"
        - "&7Максимальная высота: &f{max_height}"
        - ""
        - "&8Выберите время расширения"
        - "&8по высоте ниже."

    # Кнопка отключения (если активно)
    disable:
      slot: 13
      material: "BARRIER"
      name: "&c&lОтключить расширение"
      lore:
        - ""
        - "&7Отключить временное"
        - "&7расширение по высоте."
        - ""
        - "&cРегион вернется к"
        - "&cобычной высоте!"
        - ""
        - "&eНажмите для отключения"

    # Кнопка возврата
    back:
      slot: 22
      material: "ARROW"
      name: "&c&lНазад"
      lore:
        - ""
        - "&7Вернуться в меню региона"

    # Декоративные элементы
    filler:
      enabled: true
      material: "PURPLE_STAINED_GLASS_PANE"
      name: "&r"
      slots: [0, 1, 2, 3, 5, 6, 7, 8, 9, 17, 18, 19, 20, 21, 23, 24, 25, 26]

  # Опции расширения времени (время в секундах)
  time-options:
    # Опция 30 секунд (для тестирования)
    seconds30:
      slot: 10
      seconds: 30
      price: 100.0
      material: "COAL"
      name: "&a+30 секунд"
      lore:
        - ""
        - "&7Расширить регион по высоте"
        - "&7на &e30 секунд"
        - ""
        - "&7Цена: &6{price} монет"
        - ""
        - "&8Для тестирования"
        - "&eНажмите для покупки!"

    # Опция 2 минуты
    minutes2:
      slot: 11
      seconds: 120
      price: 200.0
      material: "IRON_INGOT"
      name: "&a+2 минуты"
      lore:
        - ""
        - "&7Расширить регион по высоте"
        - "&7на &e2 минуты"
        - ""
        - "&7Цена: &6{price} монет"
        - ""
        - "&eНажмите для покупки!"

    # Опция 1 час
    hour1:
      slot: 15
      seconds: 3600
      price: 2000.0
      material: "DIAMOND"
      name: "&a+1 час"
      lore:
        - ""
        - "&7Расширить регион по высоте"
        - "&7на &e1 час"
        - ""
        - "&7Цена: &6{price} монет"
        - ""
        - "&eНажмите для покупки!"

# Сообщения
messages:
  # Создание региона
  region-created: "&aПриват успешно создан для игрока &e{player}&a!"
  region-created-no-borders: "&7Подсветка границ отключена. Вы можете включить её через меню региона."
  region-borders-created: "&7Границы региона отмечены &cкрасной шерстью&7."
  borders-toggle-hint: "&7Совет: Вы можете включить/выключить подсветку границ через меню региона (ПКМ по центральному блоку)."

  # Сообщение о таймере
  region-timer-created: "&eВремя жизни региона: &f{time} минут. &7Не забудьте продлить!"

  # Удаление региона
  region-deleted: "&aПриват удален!"
  region-borders-restored: "&7Границы из красной шерсти восстановлены до исходного состояния."
  region-deletion-cancelled: "&7Удаление региона отменено."

  # Ошибка ломания границ
  cannot-break-border: "&cНельзя ломать границы региона! Удалите центральный блок привата."

  # Сообщения для переключения подсветки
  borders-enabled: "&a✅ Подсветка границ включена! Границы отмечены красной шерстью."
  borders-disabled: "&e⚡ Подсветка границ выключена! Границы удалены."

  # Сообщения о расширении по высоте
  height-expansion-activated: "&a✅ Регион временно расширен до максимальной высоты на {time}!"
  height-expansion-extended: "&a✅ Время расширения по высоте продлено на {time}!"
  height-expansion-disabled: "&e⚡ Временное расширение по высоте отключено. Регион вернулся к обычной высоте."
  height-expansion-expired: "&c⏰ Время расширения по высоте истекло! Регион вернулся к обычной высоте."
  height-expansion-warning: "&e⚠ Расширение по высоте истекает через {time}! Не забудьте продлить."

  # Сообщения о коллизиях
  collision-region-limit: "&c❌ Достигнут лимит приватов! ({current}/{max})"
  collision-region-overlap: "&c❌ Невозможно создать приват - пересечение с другими регионами!"
  collision-expansion-blocked: "&c❌ Невозможно расширить регион - пересечение с соседними регионами!"

  # Детальные сообщения
  collision-conflicting-owners: "&cПересечение с регионами игроков:"
  collision-owner-entry: "&c   • &f{owner}"
  collision-suggestions-header: "&e💡 Возможные решения:"
  collision-suggestion-move: "&7   • Выберите другое место"
  collision-suggestion-distance: "&7   • Отойдите подальше от чужих приватов"
  collision-suggestion-negotiate: "&7   • Договоритесь с соседями о границах"
  collision-suggestion-admin: "&7   • Обратитесь к администратору"

  # Сообщения о размерах
  size-current: "&7Текущий размер: &f{size}"
  size-planned: "&7Планируемый размер: &f{size}"
  level-current: "&7Текущий уровень: &f{level}/{max}"

  # Экономические сообщения
  economy-insufficient-funds: "&c❌ Недостаточно денег!"
  economy-need-amount: "&eНужно: &f{amount} монет"
  economy-have-amount: "&eУ вас: &f{amount} монет"
  economy-missing-amount: "&7Не хватает: {amount} монет"
  economy-charged: "&eСписано: &f{amount} монет"
  economy-refunded: "&eВозвращено: &f{amount} монет"

# Отладка
debug:
  # Основная отладка
  enabled: true
  # Логирование создания границ
  log-border-creation: false
  # Логирование размещения границ
  log-border-placement: false
  # Логирование удаления границ
  log-border-removal: false
  # Логирование обработки травы
  log-grass-processing: false
  # Логирование расширения регионов
  log-region-expansion: true
  # Логирование действий меню
  log-menu-actions: true
  # Логирование обнаружения мира
  log-world-detection: false
  # Подробный поиск границ
  verbose-border-search: false
  # Логирование состояний подсветки
  log-borders-state: false
  # Логирование восстановления при запуске
  log-startup-restoration: false
  # Логирование загрузки таймеров
  log-timer-loading: false
  # Настройки отладки коллизий
  log-collision-details: true
  log-collision-checks: true
  log-expansion-attempts: true
  log-region-boundaries: true
  log-collision-analysis: true
  # Детальная информация о пересечениях
  collision-verbose-logging: false
  collision-show-coordinates: true
  collision-show-overlapping-areas: true

# Продвинутые настройки
advanced:
  # Максимальная глубина поиска земли
  max-ground-search-depth: 50
  # Расширенная отладка
  debug:
    enabled: true
    log-border-creation: true
    log-border-removal: true
    log-border-placement: true
    log-world-detection: true
    log-stack-traces: true
    log-height-expansion: true
    log-region-operations: true

  # Безопасность операций с регионами
  safety:
    # Создавать резервные копии регионов перед изменением
    backup-before-modify: true
    # Максимальное количество попыток восстановления региона
    max-restore-attempts: 3
    # Задержка между попытками восстановления (в тиках)
    restore-attempt-delay: 20
    # Отправлять уведомления администраторам при критических ошибках
    notify-admins-on-critical-errors: true

  # Настройки расширения по высоте
  height-expansion:
    enabled: true
    # Проверять существование региона перед каждой операцией
    verify-region-exists: true
    # Задержка перед пересозданием границ после расширения (в тиках)
    border-recreation-delay: 10
    # Автоматически восстанавливать регион при ошибке расширения
    auto-restore-on-failure: true
    debug:
      enabled: true
      log-border-creation: true
      log-border-removal: true
      log-height-expansion: true
      log-region-operations: true
      log-stack-traces: true